### ISSUE TITLE
happy show live repack problem

### ISSUE THREAD

**Issue by rinnow** [imKota/qliepack#3]
As in titles I tried to repack to .pack but it didn't work well.
Even though I packed scenario in unicode after I packed to .pack it did not recognise well.
I do appriciate if you fix this problem.
Thanks for making this tool anyway.

link for trial bellow just in case.
http://www.favo-soft.jp/soft/product/happylive_showup/trial.html

**Comment by imKota** [comment]
@rinnow hello!
Download the new version **qliepackV2**.

![image](https://user-images.githubusercontent.com/24241471/116533650-4cd87580-a8ea-11eb-808a-57656d08a16e.png)

**Comment by rinnow** [comment]
@imKota 
Thanks for your lovely work!
It seems to be working perfectly.
